      INTEGER*8 FUNCTION PYDAT1_ADDRESS() 

      IMPLICIT DOUBLE PRECISION(A-H, O-Z)
      IMPLICIT INTEGER(I-N)
      COMMON/PYDAT1/MSTU(200),PARU(200),MSTJ(200),PARJ(200)
      SAVE  /PYDAT1/
      
      PYDAT1_ADDRESS = LOC(MSTU(1))

      RETURN
      END
