      INTEGER*8 FUNCTION YADAT1_ADDRESS() 

      IMPLICIT DOUBLE PRECISION(A-H, O-Z)
      IMPLICIT INTEGER(I-N)
      COMMON/YADAT1/YAPARS(20),YAFLAGS(20)
      SAVE  /YADAT1/

      YADAT1_ADDRESS = LOC(YAPARS(1))
      
      RETURN
      END
